required-players: 2
seeker-wait-time: 10
countdown-time: 15
match-time: 300

arenas:
  0:
    name: 'skeld'
    lobby-spawn:
      world: 'skeld'
      x: 28.0
      y: 18.0
      z: 109.0
      yaw: 0.0
      pitch: 0.0
    hider-spawn:
      world: 'skeld'
      x: 28.0
      y: 18.0
      z: 109.0
      yaw: 0.0
      pitch: 0.0
    seeker-spawn:
      world: 'skeld'
      x: 28.0
      y: 18.0
      z: 109.0
      yaw: 0.0
      pitch: 0.0