#Spawnpoint of Catch me if you can
seekerspawn:
  x: -302.5
  y: -12
  z: 90

hiderspawn:
  x: -302.5
  y: -12
  z: 83

spectatorspawn:
  x: -302.5
  y: -12
  z: 83

lobby:
  x: 0.5
  y: 1
  z: 0.5

world: 'world'